# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import uic
from PyQt6.QtWidgets import QLineEdit, QApplication, QPushButton, QTableWidget, QLabel, QTableWidgetItem
import base64
import cryptocode
import pyperclip


res = "111"

def encipher(origin:str,pwd:str,le_res:QLabel):
    global res
    res = cryptocode.encrypt(origin,pwd)
    le_res.setText(res)

def decrypt(origin:str,pwd:str,le_res:QLabel):
    global res
    res = cryptocode.decrypt(origin, pwd)
    le_res.setText(res)


def copy(res):
    pyperclip.copy(res)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    res = "1111"
    ui = uic.loadUi('main.ui')
    ui.show()

    #LE
    leOriginstr:QLineEdit = ui.le_orgin_str
    lePwd:QLineEdit = ui.le_deal_str

    #LB
    lbRes = ui.lb_res_str

    #BTN
    btnEncipher: QPushButton = ui.btn_encipher
    btnEncipher.clicked.connect(lambda: encipher(leOriginstr.text(),lePwd.text(),lbRes))
    btnDecrypt: QPushButton = ui.btn_decrypt
    btnDecrypt.clicked.connect(lambda: decrypt(leOriginstr.text(), lePwd.text(), lbRes))
    btnCopy: QPushButton = ui.btn_copy
    btnCopy.clicked.connect(lambda: copy(res))
    sys.exit(app.exec())

